/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ASUS
 */
public class TableMahasiswa extends javax.swing.JFrame {
       private Connection con;
       private Statement stat;
       private ResultSet res;
    /**
     * Creates new form TableMahasiswa
     */
    public TableMahasiswa() {
        initComponents();
        setTitle("Table Data Mahasiswa");
        koneksi();
        tabel();
        bara_table.setAutoCreateRowSorter(true);
    }
    
    private void koneksi (){
        try {
         Class.forName("com.mysql.jdbc.Driver");
         con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/aplikasikelas", "root", "");
         stat=con.createStatement();
         } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);}
        }
        
        private void tabel (){
        DefaultTableModel t= new DefaultTableModel();
        t.addColumn("Nim");
        t.addColumn("Nama");
        t.addColumn("Jenis Kelamin");
        t.addColumn("No HP");
        t.addColumn("Alamat");
        bara_table.setModel(t); try{ res= stat.executeQuery("select * from mahasiswa");
while (res.next()) {
    t.addRow(new Object[]{ res.getString("Nim"),
      res.getString("Nama"),
      res.getString("JenisKelamin"),
      res.getString("NoHp"),
      res.getString("Alamat")
        });
    }
}catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, e);
}    
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bara_table = new javax.swing.JTable();
        bara_mahasiswa = new javax.swing.JButton();
        bara_tabungan = new javax.swing.JButton();
        bara_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bara_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(bara_table);

        bara_mahasiswa.setText("Pilih Mahasiswa");
        bara_mahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bara_mahasiswaActionPerformed(evt);
            }
        });

        bara_tabungan.setText("Pilih Tabungan");
        bara_tabungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bara_tabunganActionPerformed(evt);
            }
        });

        bara_back.setText("Back");
        bara_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bara_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bara_mahasiswa)
                        .addGap(18, 18, 18)
                        .addComponent(bara_tabungan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bara_back))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bara_mahasiswa)
                    .addComponent(bara_tabungan)
                    .addComponent(bara_back))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Mahasiswa data = new  Mahasiswa();
    private void bara_mahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bara_mahasiswaActionPerformed
        // TODO add your handling code here:
                int index = bara_table.getSelectedRow();
        
        TableModel model = bara_table.getModel();
        
        String nim = model.getValueAt(index, 0).toString();
        String nama = model.getValueAt(index, 1).toString();
        String jk = model.getValueAt(index, 2).toString();
        String nohp = model.getValueAt(index, 3).toString();
        String alamat = model.getValueAt(index, 4).toString();
      
       
        data.setVisible(true);
        data.pack();
        data.setLocationRelativeTo(null);
        data.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        data.bara_nim.setText(nim);
        data.bara_nama.setText(nama);
        data.bara_jk.setSelectedItem(jk);
        data.bara_nohp.setText(nohp);
        data.bara_alamat.setText(alamat);
        dispose();
    }//GEN-LAST:event_bara_mahasiswaActionPerformed

    Tabungan mahasiswa = new Tabungan();
    private void bara_tabunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bara_tabunganActionPerformed
        // TODO add your handling code here:
                int index = bara_table.getSelectedRow();
        
        TableModel model = bara_table.getModel();
        
        String nama = model.getValueAt(index, 1).toString();
      
       
        mahasiswa.setVisible(true);
        mahasiswa.pack();
        mahasiswa.setLocationRelativeTo(null);
        mahasiswa.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        mahasiswa.bara_nama.setText(nama);
        dispose();
    }//GEN-LAST:event_bara_tabunganActionPerformed

    private void bara_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bara_backActionPerformed
        // TODO add your handling code here:
        new Mahasiswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_bara_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bara_back;
    private javax.swing.JButton bara_mahasiswa;
    private javax.swing.JTable bara_table;
    private javax.swing.JButton bara_tabungan;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
