/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.awt.event.KeyEvent;
import java.sql.Date;

/**
 *
 * @author ASUS
 */
public class Tabungan extends javax.swing.JFrame {
    private Connection con;
    private Statement stat;
    private ResultSet res;
    private String t, keterangan;
    private DefaultTableModel dtm;
    
    /**
     * Creates new form Tabungan
     */
    public Tabungan() {
        initComponents();
        setTitle("LAPORAN TABUNGAN");
        koneksi ();
        kosongkan ();
        tabel ();
        //rata kiri dan kanan
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(
           (screenSize.width - frameSize.width) / 3,
           (screenSize.height - frameSize.height) /4);
    }
    
    private void koneksi (){
     try {
         Class.forName("com.mysql.jdbc.Driver");
         con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/aplikasikelas", "root", "");
         stat=con.createStatement();
         } catch (Exception e) {
           JOptionPane.showMessageDialog(null, e);}   
    }
    
     private void kosongkan(){
     bara_no.setText("");
     bara_tanggal.setDate(null);
     bara_nama.setText("");
     bara_keterangan.setText("");
     bara_pembayaran.setText("");
     bara_pengeluaran.setText("");
     bara_saldoakhir.setText("");
     pembayaran.setSelected(false);
     pengeluaran.setSelected(false);
     bara_no.requestFocus();
    }
    
    private void tabel (){
        DefaultTableModel t= new DefaultTableModel();
        t.addColumn("No");
        t.addColumn("Tanggal");
        t.addColumn("Nama");
        t.addColumn("Keterangan");
        t.addColumn("Pemasukan");
        t.addColumn("Pengeluaran");
        t.addColumn("Saldo Akhir");
  
        bara_table.setModel(t); try{ res= stat.executeQuery("select * from tabungan");
    while (res.next()) {
    t.addRow(new Object[]{ 
      res.getString("No"),
      res.getString("Tanggal"),
      res.getString("Nama"),
      res.getString("Keterangan"),
      res.getString("Pemasukan"),
      res.getString("Pengeluaran"),
      res.getString("Saldo Akhir")
        });}
}catch (Exception e) {
    JOptionPane.showMessageDialog(rootPane, e);}    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bara_no = new javax.swing.JTextField();
        bara_pembayaran = new javax.swing.JTextField();
        bara_keterangan = new javax.swing.JTextField();
        bara_pengeluaran = new javax.swing.JTextField();
        bara_saldoakhir = new javax.swing.JTextField();
        bara_tanggal = new com.toedter.calendar.JDateChooser();
        pembayaran = new javax.swing.JCheckBox();
        bara_nama = new javax.swing.JTextField();
        bara_lihat = new javax.swing.JButton();
        pengeluaran = new javax.swing.JCheckBox();
        TABUNGAN = new javax.swing.JTextField();
        bara_edit = new javax.swing.JButton();
        bara_simpan = new javax.swing.JButton();
        bara_clear = new javax.swing.JButton();
        bara_hapus = new javax.swing.JButton();
        bara_search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bara_table = new javax.swing.JTable();
        bara_menu = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("No.");

        jLabel2.setText("Tanggal");

        jLabel3.setText("Keterangan");

        jLabel4.setText("Rp.");

        jLabel5.setText("Nama");

        jLabel6.setText("Rp.");

        jLabel7.setText("Saldo Akhir");

        jLabel8.setText("Tabungan/2 Minggu Rp.");

        bara_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bara_noActionPerformed(evt);
            }
        });
        bara_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bara_noKeyTyped(evt);
            }
        });

        bara_pembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bara_pembayaranKeyTyped(evt);
            }
        });

        bara_keterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bara_keteranganActionPerformed(evt);
            }
        });

        bara_pengeluaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bara_pengeluaranKeyTyped(evt);
            }
        });

        bara_saldoakhir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bara_saldoakhirActionPerformed(evt);
            }
        });
        bara_saldoakhir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bara_saldoakhirKeyTyped(evt);
            }
        });

        pembayaran.setText("Pembayaran");
        pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranActionPerformed(evt);
            }
        });

        bara_lihat.setText("Lihat");
        bara_lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bara_lihatActionPerformed(evt);
            }
        });

        pengeluaran.setText("Pengeluaran");
        pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengeluaranActionPerformed(evt);
            }
        });

        bara_edit.setText("Edit");
        bara_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bara_editActionPerformed(evt);
            }
        });

        bara_simpan.setText("Simpan");
        bara_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bara_simpanActionPerformed(evt);
            }
        });

        bara_clear.setText("Clear");
        bara_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bara_clearActionPerformed(evt);
            }
        });

        bara_hapus.setText("Hapus");
        bara_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bara_hapusActionPerformed(evt);
            }
        });

        bara_search.setText("Search");
        bara_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bara_searchActionPerformed(evt);
            }
        });

        bara_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bara_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bara_tableMouseClicked(evt);
            }
        });
        bara_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bara_tableKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(bara_table);

        bara_menu.setText("Menu");
        bara_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bara_menuActionPerformed(evt);
            }
        });

        jLabel9.setText("Rp.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bara_edit)
                                        .addGap(27, 27, 27)
                                        .addComponent(bara_simpan)
                                        .addGap(29, 29, 29)
                                        .addComponent(bara_clear)
                                        .addGap(28, 28, 28)
                                        .addComponent(bara_hapus)
                                        .addGap(18, 18, 18)
                                        .addComponent(bara_search)
                                        .addGap(18, 18, 18)
                                        .addComponent(bara_menu)
                                        .addGap(0, 31, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel5))
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bara_lihat)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(bara_no, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(bara_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(bara_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(pengeluaran)
                                                            .addComponent(pembayaran))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel6)
                                                            .addComponent(jLabel4)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(21, 21, 21)
                                                        .addComponent(jLabel7)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel9)))))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(bara_saldoakhir)
                                            .addComponent(bara_pembayaran)
                                            .addComponent(bara_pengeluaran)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(39, 39, 39)
                                .addComponent(bara_keterangan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(TABUNGAN))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bara_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bara_pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bara_saldoakhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pengeluaran)
                            .addGap(25, 25, 25))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(pembayaran))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel4)
                            .addGap(34, 34, 34))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bara_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bara_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bara_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))))
                .addGap(9, 9, 9)
                .addComponent(bara_lihat)
                .addGap(0, 0, 0)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TABUNGAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bara_keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bara_edit)
                    .addComponent(bara_search)
                    .addComponent(bara_hapus)
                    .addComponent(bara_clear)
                    .addComponent(bara_simpan)
                    .addComponent(bara_menu))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bara_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bara_noActionPerformed
        // TODO add your handling code here:
                try{
            res=stat.executeQuery("select * from tabungan where "+ "No='" + bara_no.getText()
                +"'" ); while (res.next())
                { bara_tanggal.setDate (res.getDate("Tanggal"));
                bara_nama.setText(res.getString("Nama"));
                bara_keterangan.setText(res.getString("Keterangan"));
                bara_pembayaran.setText(res.getString("Pemasukan"));
                bara_pengeluaran.setText(res.getString("Pengeluaran"));
                bara_saldoakhir.setText(res.getString("Saldo Akhir"));
                }    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_bara_noActionPerformed

    private void pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranActionPerformed
        // TODO add your handling code here:
        keterangan = "Uang Masuk";
        pengeluaran.setSelected(false);
        bara_keterangan.setText(""+keterangan);
    }//GEN-LAST:event_pembayaranActionPerformed

    private void pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengeluaranActionPerformed
        // TODO add your handling code here:
        keterangan = "Uang Keluar";
        pembayaran.setSelected(false);
        bara_keterangan.setText(""+keterangan);
    }//GEN-LAST:event_pengeluaranActionPerformed

    private void bara_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bara_simpanActionPerformed
        // TODO add your handling code here:
                String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm=new SimpleDateFormat(tampilan);
        String Tanggal=String.valueOf(fm.format(bara_tanggal.getDate()));
        
        try {
         stat.executeUpdate("insert into tabungan values ("
             + "'" + bara_no.getText()+"',"
             + "'" + Tanggal+"',"
             + "'" + bara_nama.getText()+"',"
             + "'" + bara_keterangan.getText()+"',"
             + "'" + bara_pembayaran.getText()+"',"
             + "'" + bara_pengeluaran.getText()+"',"
             + "'" + bara_saldoakhir.getText()+"')");
         kosongkan();
         JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data");
         new Tabungan().setVisible(true);
         dispose();
         } catch (Exception e) {
         JOptionPane.showMessageDialog(null, "Gagal Menyimpan Data! : "+e);
        }
    }//GEN-LAST:event_bara_simpanActionPerformed

    private void bara_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bara_editActionPerformed
        // TODO add your handling code here:
                int ok=JOptionPane.showConfirmDialog(null,"Apakah yakin ingin mengedit data?","Confirmation",
                JOptionPane.YES_NO_OPTION);
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm=new SimpleDateFormat(tampilan);
        String Tanggal=String.valueOf(fm.format(bara_tanggal.getDate()));
    try{
    String sql = "update tabungan set No=?,Tanggal=?,Nama=?,Pemasukan=?,Pengeluaran=?,"
            + "Saldo Akhir=?,Keterangan=? where No='"
                    + bara_no.getText()+"'";
    PreparedStatement st=con.prepareStatement(sql);
    if(ok==0){
    try{
    st.setString(1,bara_no.getText());
    st.setString(2,Tanggal);
    st.setString(3,bara_nama.getText());
    st.setString(7,bara_keterangan.getText());
    st.setString(4,bara_pembayaran.getText());
    st.setString(5,bara_pengeluaran.getText());
    st.setString(6,bara_saldoakhir.getText());
    st.executeUpdate();
    kosongkan();
    JOptionPane.showMessageDialog(null,"Edit Data Sukses");
    new Tabungan().setVisible(true);
    dispose();
    }catch (Exception e){
    JOptionPane.showMessageDialog(null, "Edit Data Gagal");}}
    }catch (Exception e){}
    }//GEN-LAST:event_bara_editActionPerformed

    private void bara_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bara_clearActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_bara_clearActionPerformed

    private void bara_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bara_hapusActionPerformed
        // TODO add your handling code here:
                int ok=JOptionPane.showConfirmDialog(null,"Apakah yakin ingin menghapus data?","Confirmation",
                JOptionPane.YES_NO_OPTION);
         try{
             String sql="delete from tabungan where No='"+bara_no.getText()+"'";
             PreparedStatement st=con.prepareStatement (sql);
             st.executeUpdate();
             kosongkan();
             JOptionPane.showMessageDialog(null, "Delete Data Sukses");
             new Tabungan().setVisible(true);
             dispose();
         } catch (Exception e)
         {
             JOptionPane.showMessageDialog(null, "Delete Data Gagal");
         }
    }//GEN-LAST:event_bara_hapusActionPerformed

    private void bara_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bara_searchActionPerformed
        // TODO add your handling code here:
                try {
    res=stat.executeQuery("select * from tabungan where "+ "No='" +bara_no.getText()
    +"'" ); while (res.next())
    { bara_tanggal.setDate(res.getDate("Tanggal"));
      bara_nama.setText(res.getString("Nama"));
      bara_keterangan.setText(res.getString("Keterangan"));
      bara_pembayaran.setText(res.getString("Pemasukan"));
      bara_pengeluaran.setText(res.getString("Pengeluaran"));
      bara_saldoakhir.setText(res.getString("Saldo Akhir"));
    }
}catch (Exception e) {
JOptionPane.showMessageDialog(rootPane, e);
}
    }//GEN-LAST:event_bara_searchActionPerformed

    private void bara_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bara_menuActionPerformed
        // TODO add your handling code here:
                new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_bara_menuActionPerformed

    private void bara_lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bara_lihatActionPerformed
        // TODO add your handling code here:
                new TableMahasiswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_bara_lihatActionPerformed

    private void bara_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bara_tableMouseClicked
        // TODO add your handling code here:
                int i = bara_table.getSelectedRow();
    if(i==-1){
    return;
    }
    String code = (String)bara_table.getValueAt(i,0);
    String code1 = (String)bara_table.getValueAt(i,1);
    String code2 = (String)bara_table.getValueAt(i,2);
    String code3 = (String)bara_table.getValueAt(i,3);
    String code4 = (String)bara_table.getValueAt(i,4);
    String code5 = (String)bara_table.getValueAt(i,5);
    String code6 = (String)bara_table.getValueAt(i,6);
    
    bara_no.setText(code);
    bara_tanggal.setDateFormatString(code1);
    bara_nama.setText(code2);
    bara_keterangan.setText(code3);
    bara_pengeluaran.setText(code4);
    bara_saldoakhir.setText(code5);
    bara_pembayaran.setText(code6);
    }//GEN-LAST:event_bara_tableMouseClicked

    private void bara_pembayaranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bara_pembayaranKeyTyped
        // TODO add your handling code here:
                char bara=evt.getKeyChar();
        if(!(Character.isDigit(bara)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_bara_pembayaranKeyTyped

    private void bara_pengeluaranKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bara_pengeluaranKeyTyped
        // TODO add your handling code here:
        char bara=evt.getKeyChar();
        if(!(Character.isDigit(bara)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_bara_pengeluaranKeyTyped

    private void bara_saldoakhirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bara_saldoakhirKeyTyped
        // TODO add your handling code here:
                char bara=evt.getKeyChar();
        if(!(Character.isDigit(bara)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_bara_saldoakhirKeyTyped

    private void bara_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bara_noKeyTyped
        // TODO add your handling code here:
                char bara=evt.getKeyChar();
        if(!(Character.isDigit(bara)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_bara_noKeyTyped

    private void bara_saldoakhirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bara_saldoakhirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bara_saldoakhirActionPerformed

    private void bara_tableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bara_tableKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_bara_tableKeyTyped

    private void bara_keteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bara_keteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bara_keteranganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabungan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tabungan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TABUNGAN;
    private javax.swing.JButton bara_clear;
    private javax.swing.JButton bara_edit;
    private javax.swing.JButton bara_hapus;
    private javax.swing.JTextField bara_keterangan;
    private javax.swing.JButton bara_lihat;
    private javax.swing.JButton bara_menu;
    public javax.swing.JTextField bara_nama;
    private javax.swing.JTextField bara_no;
    private javax.swing.JTextField bara_pembayaran;
    private javax.swing.JTextField bara_pengeluaran;
    private javax.swing.JTextField bara_saldoakhir;
    private javax.swing.JButton bara_search;
    private javax.swing.JButton bara_simpan;
    public javax.swing.JTable bara_table;
    private com.toedter.calendar.JDateChooser bara_tanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox pembayaran;
    private javax.swing.JCheckBox pengeluaran;
    // End of variables declaration//GEN-END:variables
}
